name: Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve expo-esim-provisioning? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: Is your feature request related to a problem? Describe the use-case clearly.
      placeholder: "I'm trying to do X, but the current API doesn't support..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature you'd like. Include a proposed API shape if applicable.
      placeholder: |
        Add a new `deleteEsimProfile(iccid)` function that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered.

  - type: dropdown
    id: platform
    attributes:
      label: Target platform
      options:
        - Android
        - iOS
        - Both
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority for your use-case
      options:
        - Nice to have
        - Important
        - Blocking (I can't ship without this)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, native API references, or relevant links.
